/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

/**
 *
 * @author 24.01465-6
 */
public class TelaLoginAdm extends javax.swing.JFrame {

    /**
     * Creates new form TelaLoginAdm
     */
    public TelaLoginAdm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        erroLoginInvalidoLabel = new javax.swing.JLabel();
        senhaAdmPasswordField = new javax.swing.JPasswordField();
        emailAdmTextField = new javax.swing.JTextField();
        entrarAdmButton = new javax.swing.JButton();
        telaLoginAdmLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        erroLoginInvalidoLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        erroLoginInvalidoLabel.setForeground(new java.awt.Color(255, 29, 51));
        erroLoginInvalidoLabel.setText("E-mail ou senha inválidos!");
        getContentPane().add(erroLoginInvalidoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 363, 390, 20));

        senhaAdmPasswordField.setBackground(new java.awt.Color(196, 196, 196));
        senhaAdmPasswordField.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        senhaAdmPasswordField.setForeground(new java.awt.Color(51, 51, 51));
        senhaAdmPasswordField.setBorder(null);
        senhaAdmPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaAdmPasswordFieldActionPerformed(evt);
            }
        });
        getContentPane().add(senhaAdmPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 410, 30));

        emailAdmTextField.setBackground(new java.awt.Color(196, 196, 196));
        emailAdmTextField.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        emailAdmTextField.setForeground(new java.awt.Color(51, 51, 51));
        emailAdmTextField.setBorder(null);
        emailAdmTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailAdmTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(emailAdmTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 255, 410, 30));

        entrarAdmButton.setBorder(null);
        entrarAdmButton.setContentAreaFilled(false);
        entrarAdmButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                entrarAdmButtonFocusGained(evt);
            }
        });
        entrarAdmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarAdmButtonActionPerformed(evt);
            }
        });
        getContentPane().add(entrarAdmButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, 460, 40));

        telaLoginAdmLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TELA_LOGIN_ADM.png"))); // NOI18N
        telaLoginAdmLabel.setText("jLabel1");
        getContentPane().add(telaLoginAdmLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 3, 1000, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entrarAdmButtonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_entrarAdmButtonFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_entrarAdmButtonFocusGained

    private void entrarAdmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarAdmButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entrarAdmButtonActionPerformed

    private void emailAdmTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailAdmTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailAdmTextFieldActionPerformed

    private void senhaAdmPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaAdmPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaAdmPasswordFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLoginAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLoginAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLoginAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLoginAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLoginAdm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField emailAdmTextField;
    private javax.swing.JButton entrarAdmButton;
    private javax.swing.JLabel erroLoginInvalidoLabel;
    private javax.swing.JPasswordField senhaAdmPasswordField;
    private javax.swing.JLabel telaLoginAdmLabel;
    // End of variables declaration//GEN-END:variables
}
