/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import com.mycompany.policards.Usuario;
import javax.swing.JOptionPane;
import persistencia.UsuarioDAO;


/**
 *
 * @author AMD
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        super ("Policards");
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginButton = new javax.swing.JButton();
        loginTextField = new javax.swing.JTextField();
        senhaPasswordField = new javax.swing.JPasswordField();
        registrarButton = new javax.swing.JButton();
        esqueciSenhaButton = new javax.swing.JButton();
        telaLoginLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(null);
        setSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginButton.setBorder(null);
        loginButton.setContentAreaFilled(false);
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(643, 815, 630, 56));

        loginTextField.setBackground(new java.awt.Color(196, 196, 196));
        loginTextField.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        loginTextField.setForeground(new java.awt.Color(51, 51, 51));
        loginTextField.setBorder(null);
        loginTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(loginTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 490, 575, 50));

        senhaPasswordField.setBackground(new java.awt.Color(196, 196, 196));
        senhaPasswordField.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        senhaPasswordField.setForeground(new java.awt.Color(51, 51, 51));
        senhaPasswordField.setBorder(null);
        senhaPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaPasswordFieldActionPerformed(evt);
            }
        });
        getContentPane().add(senhaPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 610, 575, 50));

        registrarButton.setBorder(null);
        registrarButton.setContentAreaFilled(false);
        getContentPane().add(registrarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 900, 350, 30));

        esqueciSenhaButton.setBorder(null);
        esqueciSenhaButton.setContentAreaFilled(false);
        getContentPane().add(esqueciSenhaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 690, 190, 30));

        telaLoginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        telaLoginLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TELA_LOGIN.png"))); // NOI18N
        telaLoginLabel.setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().add(telaLoginLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void senhaPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaPasswordFieldActionPerformed

    private void loginTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginTextFieldActionPerformed
    
    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        //pega o login do usuário
        String email = loginTextField.getText();
        //pega a senha do usuário como char[] e converte para String
        String senha = new String(senhaPasswordField.getPassword());

        try {
            UsuarioDAO dao = new UsuarioDAO();
            Usuario usuario = dao.autenticar(email, senha);
            if (usuario != null) {
                JOptionPane.showMessageDialog(null, "Bem vindo, " + usuario.getEmail() + "!");
                new TelaModos().setVisible(true);
                this.dispose();
            }
            else {
                JOptionPane.showMessageDialog(null, "Usuário inválido");
                new TelaLogin().setVisible(true);
                this.dispose();
            }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Problemas técnicos. Tente novamente mais tarde");
            e.printStackTrace();
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton esqueciSenhaButton;
    private javax.swing.JButton loginButton;
    private javax.swing.JTextField loginTextField;
    private javax.swing.JButton registrarButton;
    private javax.swing.JPasswordField senhaPasswordField;
    private javax.swing.JLabel telaLoginLabel;
    // End of variables declaration//GEN-END:variables
}
