/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import persistencia.ConnectionFactory;

/**
 *
 * @author AMD
 */
public class TelaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cadastroButton = new javax.swing.JButton();
        cadastroTextField = new javax.swing.JTextField();
        senhaConfirmeCadastroPassworldField = new javax.swing.JPasswordField();
        senhaCadastroPasswordField = new javax.swing.JPasswordField();
        telaCadastroLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1440, 1024));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cadastroButton.setBorder(null);
        cadastroButton.setContentAreaFilled(false);
        cadastroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cadastroButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(645, 880, 630, 60));

        cadastroTextField.setBackground(new java.awt.Color(196, 196, 196));
        cadastroTextField.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        cadastroTextField.setForeground(new java.awt.Color(51, 51, 51));
        cadastroTextField.setBorder(null);
        cadastroTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(cadastroTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 500, 580, 50));

        senhaConfirmeCadastroPassworldField.setBackground(new java.awt.Color(196, 196, 196));
        senhaConfirmeCadastroPassworldField.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        senhaConfirmeCadastroPassworldField.setBorder(null);
        getContentPane().add(senhaConfirmeCadastroPassworldField, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 750, 580, 50));

        senhaCadastroPasswordField.setBackground(new java.awt.Color(196, 196, 196));
        senhaCadastroPasswordField.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        senhaCadastroPasswordField.setBorder(null);
        getContentPane().add(senhaCadastroPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 620, 580, 50));

        telaCadastroLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TELA_CADASTRO.png"))); // NOI18N
        telaCadastroLabel.setText("jLabel3");
        getContentPane().add(telaCadastroLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastroTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastroTextFieldActionPerformed

    private void cadastroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroButtonActionPerformed
        
    }//GEN-LAST:event_cadastroButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastroButton;
    private javax.swing.JTextField cadastroTextField;
    private javax.swing.JPasswordField senhaCadastroPasswordField;
    private javax.swing.JPasswordField senhaConfirmeCadastroPassworldField;
    private javax.swing.JLabel telaCadastroLabel;
    // End of variables declaration//GEN-END:variables
}
